# ------------------------------------------------------------------------------------------------ #
# Annotate Orthogroups
#
# This script combines GO Terms annotated by Funannotate (InterPro) and Wei2GO.
# Additionally, this script looks to assign gene-symbols to orthogroups where possible
# using Funannotate, UniProtKB annotations and NCBI assigned annotations using NCBI samples.
#
# ------------------------------------------------------------------------------------------------ #

# ------------------------------------------------------------------------------------------------ #
# Libraries
suppressPackageStartupMessages({
  library(here)
  library(fs)
  library(tidyverse)
})

# ------------------------------------------------------------------------------------------------ #
# Orthogroup information (OrthoFinder)
orthogroups <- read_tsv(
  file = here('results', 'orthologs', 'orthofinder' ,'Results_mmseqs', 'Orthogroups', 'Orthogroups.tsv'),
  col_names = TRUE,
  col_types = cols()
)

# Single copy orthologs
orthogroups.sc <- read_tsv(
  file = here('results', 'orthologs', 'orthofinder' ,'Results_mmseqs', 'Orthogroups', 'Orthogroups_SingleCopyOrthologues.txt'),
  col_names = 'Orthogroup',
  col_types = cols()
)

# Single copy orthologs only
single.copy.orthologs <- left_join(orthogroups.sc, orthogroups) %>%
  pivot_longer(
    names_to = 'species',
    values_to = 'TranscriptID', 2:12
  )

# ------------------------------------------------------------------------------------------------ #
# Funannotate GO-Map tables (Generated by 'funAnn2Go')
go.funannotate <- fs::dir_ls(
  path = here('results', 'annotate-orthogroups', 'go-tables-funannotate'),
  glob = "*.tsv"
) %>%
  read_tsv(
    col_names = c('GeneID', 'TranscriptID', 'Symbol', 'GO'),
    col_types = cols(),
    id = 'species'
  ) %>%
  mutate(
    species = sub('-.*', '', basename(species))
  ) %>%
  rename(
    GO_funannotate = GO
  ) %>%
  select(-GeneID)

# ------------------------------------------------------------------------------------------------ #
# Wei2GO
go.wei2go <- fs::dir_ls(
  path = here('results', 'annotate-orthogroups', 'wei2go'),
  glob = '*.tsv',
) %>%
  vroom::vroom(
    col_names = TRUE,
    col_types = cols(),
    id = 'species',
    col_select = c('species', 'Protein', `GO term`)
  ) %>%
  mutate(
    species = sub('.tsv', '', basename(species)),
    Protein = ifelse(species == 'naja_naja', sub("WGS:SOZL", "WGS_SOZL", Protein), Protein)
  ) %>%
  rename(
    TranscriptID = Protein,
    GO_wei2go = `GO term`
  )

# ------------------------------------------------------------------------------------------------ #
# Best-BLAST GO Term annotations
genes.blast <- read_csv(
  file = here('results', 'annotate-orthogroups', 'blast-to-swissProt', 'annotate-blast-hits', 'blast-GO-annotations.csv'),
  col_names = TRUE,
  col_types = cols()
) %>%
  rename(
    TranscriptID = qaccver,
    GO_blast = GO
  ) %>%
  # ONLY FOR N. naja
  mutate(
    TranscriptID = ifelse(species == 'naja_naja', sub("WGS:SOZL", "WGS_SOZL", TranscriptID), TranscriptID)
  )

# ------------------------------------------------------------------------------------------------ #
# Single copy ortholog object
single.copy.orthologs.go <- reduce(
  .x = list(single.copy.orthologs, go.funannotate, go.wei2go, genes.blast ),
  .f = left_join
) %>%
group_by(Orthogroup) %>%
  nest() %>%
  pmap_dfr(~{
    go.terms <- c(..2[["GO_funannotate"]], ..2[["GO_wei2go"]]) %>%
      na.omit() %>%
      as.character() %>%
      str_split(string = ., pattern = " ") %>%
      unlist() %>%
      unique() %>%
      paste(collapse = ', ')

    symbol <- c(..2[['symbol']], ..2[['Symbol']], ..2[["ncbi_symbol"]]) %>%
      na.omit() %>%
      as.character()

    # If a symbol is present
    if (!is_empty(symbol)) {
      symbol <- symbol %>%
        toupper() %>%
        unique()

      # Check if there is one unique symbol or multiple
      if(length(symbol) > 1) {
        # If removing a tralining '_[0-9]' results in a single ID, keep that
        m <- symbol %>%
          gsub('_[0-9]$', '', .) %>%
          unique()
        symbol <- ifelse(length(m) == 1, m, symbol)
      }
    } else {
      symbol = NA_character_
    }

    tibble(
      "Orthogroup" = unique(..1),
      "Symbol" = ifelse(length(symbol) > 1, paste(symbol, collapse = ", "), symbol),
      "GO Terms" = ifelse(go.terms == '', NA_character_, go.terms),
    )
  }) %>%
  arrange('Orthogroup')

# ------------------------------------------------------------------------------------------------ #
# Write to file
write_csv(
  x = single.copy.orthologs.go,
  file = here('results', 'single-copy-orthogroup-GO-symbol.csv'),
  col_names = TRUE,
  na = '', quote = 'none'
)
