# ------------------------------------------------------------------------------------------------ #
# Hyphy/CodeML overlap
#
# This script processes the selection results generated by HyPhy and PAML. The results we work with
# include three separate selection testing runs:
#   - HyPhy: BUSTED-PH where Marine snakes are marked as 'test' (Terrestrial are 'background')
#   - HyPhy: BUSTED-PH where Terrestrial snakes are marked as 'test' (Marine are 'background')
#   - PAML: Branch-Site models were used to test for selection in Marine snakes (Foreground). To
#           ensure there was no signal of PS in the background branches, Marine snakes were dropped
#           and Site models were run on ONLY the Terrestrial snakes to test for positive selection.
#
# Positively selected genes (PSGs) are classified into three categories:
#   1. Marine specific: PSGs reported by both BUSTED-PH and PAML (Marine foreground/test).
#   2. Terrestrial specific: PSGs reported by both BUSTED-PH and PAML (Uses PAML drop-out tests for
#      evidence of selection in the Terrestrial snakes).
#   3. Shared: These are genes were there is evidence of positive selection in both the terrestrial
#      AND Marine snakes. These genes must be reported by both BUSTED-PH and PAML.
#
# NOTE: The RELAX runs for the orthologs below failed. This is seemingly due to the high sequence
# similarity in the Hydrophis snakes.
#   - OG0005841
#   - OG0010444
#   - OG0009807
#   - OG0008178
#   - OG0007258

# ------------------------------------------------------------------------------------------------ #
# Libraries
library(tidyverse)
library(here)
library(fs)

# Loading for the pvalue correction functions I've written
source(here('selection', 'scripts', 'hyphy-parsing', 'general.R'))
source(here('selection', 'scripts', 'paml-parsing', 'general.R'))

# ------------------------------------------------------------------------------------------------ #
# Output directory
outdir <- here('selection','results-13','results-PSGs')
dir_create(outdir)

# ------------------------------------------------------------------------------------------------ #
# Load Hyphy and CodeML results
# These were generated using the previous script - 00-parse-hyphy.R and by default (for the PAML
# results) by the selection pipeline.

bustedph.13 <- read_rds(here('selection', 'r-data', 'busted-ph-13.rds'))
bustedph.13.terrestrial <- read_rds(here('selection', 'r-data', 'busted-ph-13-terrestrial.rds'))
relax.13 <- read_rds(here('selection', 'r-data', 'relax-13.rds'))

# Keep only Branch-Site comparisons (remove M0 as this was simply used to get initial tree values)
paml.13 <- read_csv(
  file = here('selection', 'results-13', 'paml', 'lrt-pval-comparison.csv'),
  col_names = TRUE,
  col_types = cols(),
  col_select = -signal
) |>
  filter(null_x == 'bsA1', alt_x == 'bsA', null_y == 'M1', alt_y == 'M2')

# ------------------------------------------------------------------------------------------------ #
# Correct P-values for multiple testing
# The null hypothesis is that all genes are neutral (unlikely, but needs to be accounted for),
# meaning if we tested e.g. 10,000 orthologs at an alpha of 0.05, we'd end up with 500 false +'ves.
# A Benjamini & Hochberg (1995) - FDR - correction is applied to each dataset to account for
# multiple testing.
bustedph.13$`test results corrected` <- pcorrBUSTEDPH(
  bustedph.13,
  p = 0.01,
  corrMethod = 'fdr'
)
bustedph.13$`test results corrected` <- mutate(
  bustedph.13$`test results corrected`,
  file = sub('.clean', '', file)
)

bustedph.13.terrestrial$`test results corrected` <- pcorrBUSTEDPH(
  bustedph.13.terrestrial,
  p = 0.01,
  corrMethod = 'fdr'
)
bustedph.13.terrestrial$`test results corrected` <- mutate(
  bustedph.13.terrestrial$`test results corrected`,
  file = sub('.clean', '', file)
)

relax.13$`test results corrected` <- pcorrRELAX(
  relax.13,
  p = 0.01,
  corrMethod = 'fdr'
)
relax.13$`test results corrected` <- mutate(
  relax.13$`test results corrected`,
  file = sub('.clean', '', file)
)

paml.13 <- pcorrPAML(
  df = paml.13,
  p = 0.01,
  method = 'fdr'
)

# ------------------------------------------------------------------------------------------------ #
# Positively selected genes: Unique to Marine AND Terrestrial snakes
# PAML -> Only genes where no signal of selection in background branches after dropping foreground
# HyPhy -> Only 'selection associated with trait' entries (FG/BG dist. can be the same)
# PSGs MUST be predicted by both tools

# Marine (Hydrophis) # 1,390
psg.marine.hyphy.paml <- bustedph.13$`test results corrected` |>
  left_join(paml.13) |>
  filter(
    str_detect(result, pattern = 'Selection associated with trait'),
    signal == 'PS_fg'
  ) |>
  pull(file)

write_lines(
  x = psg.marine.hyphy.paml,
  file = here(outdir,'PSGs-marine.txt')
)

# Terrestrial # 488
psg.terrestrial.hyphy.paml <- bustedph.13.terrestrial$`test results corrected` |>
  left_join(paml.13) |>
  filter(
    str_detect(result, pattern = 'Selection associated with trait'),
    signal == 'PS_bg'
  ) |>
  pull(file)

write_lines(
  x = psg.terrestrial.hyphy.paml,
  file = here(outdir,'PSGs-terrestrial.txt')
)

# Sanity check: No Marine genes should be in Terrestrial genes
table(psg.marine.hyphy.paml %in% psg.terrestrial.hyphy.paml)

# ------------------------------------------------------------------------------------------------ #
# Positively selected genes: Signal in BOTH Terrestrial/Marine
# HyPhy -> Selection acting on FG and BG branches (Dist. can be significantly different or the same)
# PAML -> Reported as PS in both BG and FG after performing dropout analysis
# PSGs MUST be predicted by both tools

# PSGs shared by Marine and Terrestrial snakes # 529
psg.shared.hyphy.paml <- bustedph.13$`test results corrected`|>
  filter(str_detect(result, 'Selection acting on branches with phenotype')) |>
  select(file) |>
  left_join(bustedph.13.terrestrial$`test results corrected`) |>
  filter(str_detect(result, 'Selection acting on branches with phenotype')) |>
  select(file) |>
  left_join(paml.13) |>
  filter(signal == 'PS_fg_bg') |>
  pull(file)

write_lines(
  x = psg.shared.hyphy.paml,
  file = here(outdir, 'PSGs-shared.txt')
)

# Sanity check: No shared genes should be in Marine/Terrestrial unique PSGs
table(c(psg.marine.hyphy.paml, psg.terrestrial.hyphy.paml) %in% psg.shared.hyphy.paml)

# ------------------------------------------------------------------------------------------------ #
# Insignificant genes: Genes not under selection in either Marine OR Terrestrial
# Thes are genes that are not identified as being under positive selection in Marine, Terrestrial
# or shared conditions. I.e. these are the genes that are left over that failed to be included
# in any of the gene lists above.

# All PSGs (unique/shared)
all.psg <- c(psg.marine.hyphy.paml, psg.terrestrial.hyphy.paml, psg.shared.hyphy.paml)

# Neutral/non-PSG genes in dataset # 6,261
paml.13$file[! paml.13$file %in% all.psg] |>
  write_lines(
    file = here(outdir, 'neutral-genes.txt')
  )

# ------------------------------------------------------------------------------------------------ #
# Relaxation/Intensification
# Write RELAX results to file after classifying if:
#   - The orthogroups reach significance or not in the Marine clade
#   - Whether there is a signal of intensification/relaxation of selection
relax.13$`test results corrected` |>
  rename(k = `relaxation or intensification parameter`) |>
  mutate(
    signif = ifelse(adj_pval <= 0.01, 'Significant', 'Insignificant'),
    grouping = case_when(
      k > 1 ~ 'Intensification',
      k < 1 ~ 'Relaxation',
      k == 1 ~ 'Neutral'
    )
  ) |>
  write_csv(
    file = here(outdir,'relax-table.csv'),
    col_names = TRUE
  )
