# ------------------------------------------------------------------------------------------------ #
# Hyphy/CodeML overlap
#
# This script processes the selection results generated by HyPhy and PAML. The results we work with
# include three separate selection testing runs:
#   - HyPhy: BUSTED-PH where Marine snakes are marked as 'test' (Terrestrial are 'background')
#   - HyPhy: BUSTED-PH where Terrestrial snakes are marked as 'test' (Marine are 'background')
#   - PAML: Branch-Site models were used to test for selection in Marine snakes (Foreground). To
#           ensure there was no signal of PS in the background branches, Marine snakes were dropped
#           and Site models were run on ONLY the Terrestrial snakes to test for positive selection.
#
# Positively selected genes (PSGs) are classified into three categories:
#   1. Marine specific: PSGs reported by both BUSTED-PH and PAML (Marine foreground/test).
#   2. Terrestrial specific: PSGs reported by both BUSTED-PH and PAML (Uses PAML drop-out tests for
#      evidence of selection in the Terrestrial snakes).
#   3. Shared: These are genes were there is evidence of positive selection in both the terrestrial
#      AND Marine snakes. These genes must be reported by both BUSTED-PH and PAML.
#
# NOTE: The RELAX runs for the orthologs below failed. This is seemingly due to the high sequence
# similarity in the Hydrophis snakes.
#   - OG0007246
#   - OG0007250
#   - OG0009921

# ------------------------------------------------------------------------------------------------ #
# Libraries
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(fs)
})

# Loading for the pvalue correction functions I've written
source(here('selection', 'scripts', 'hyphy-parsing', 'general.R'))
source(here('selection', 'scripts', 'paml-parsing', 'general.R'))

# ------------------------------------------------------------------------------------------------ #
# Output directory
outdir <- here('selection','results','results-PSGs')
dir_create(outdir)

# ------------------------------------------------------------------------------------------------ #
# Load Hyphy and CodeML results (RDS files generated by 04-parse-hyphy.R)
bustedph <- read_rds(here('selection', 'r-data', 'busted-ph.rds'))
bustedph.terrestrial <- read_rds(here('selection', 'r-data', 'busted-ph-terrestrial.rds'))
relax <- read_rds(here('selection', 'r-data', 'relax.rds'))

# Keep only Branch-Site comparisons (remove M0 as this was simply used to get initial tree values)
paml <- read_csv(
  file = here('selection', 'results', 'paml', 'lrt-pval-comparison.csv'),
  col_names = TRUE,
  col_types = cols(),
  col_select = -signal
) |>
  filter(null_x == 'bsA1', alt_x == 'bsA', null_y == 'M1', alt_y == 'M2')

# ------------------------------------------------------------------------------------------------ #
# Correct P-values for multiple testing
# The null hypothesis is that all genes are neutral (unlikely, but needs to be accounted for),
# meaning if we tested e.g. 10,000 orthologs at an alpha of 0.05, we'd end up with 500 false +'ves.
# A Benjamini & Hochberg (1995) - FDR - correction is applied to each dataset

# Positively selected genes: # 1,612
bustedph$`test results corrected` <- pcorrBUSTEDPH(
  bustedph,
  p = 0.01,
  corrMethod = 'fdr'
)
bustedph$`test results corrected` <- mutate(
  bustedph$`test results corrected`,
  file = sub('.clean', '', file)
)

bustedph$`test results corrected` |>
  write_csv(
    file = here('selection','results','results-PSGs','PSGs-bustedph-corrected.csv'),
    col_names = TRUE
  )

# Positively selected genes (terrestrial)
bustedph.terrestrial$`test results corrected` <- pcorrBUSTEDPH(
  bustedph.terrestrial,
  p = 0.01,
  corrMethod = 'fdr'
)
bustedph.terrestrial$`test results corrected` <- mutate(
  bustedph.terrestrial$`test results corrected`,
  file = sub('.clean', '', file)
)

# RELAX results
relax$`test results corrected` <- pcorrRELAX(
  relax,
  p = 0.01,
  corrMethod = 'fdr'
)
relax$`test results corrected` <- mutate(
  relax$`test results corrected`,
  file = sub('.clean', '', file)
)

relax$`test results corrected` |>
  write_csv(
    file = here('selection','results','results-PSGs','PSGs-relax-corrected.csv'),
    col_names = TRUE
  )

# Positively selected genes (PAML): # 2,674
paml <- pcorrPAML(
  df = paml,
  p = 0.01,
  method = 'fdr'
)

paml |>
  write_csv(
    file = here('selection','results','results-PSGs','PSGs-paml-corrected.csv'),
    col_names = TRUE
  )

# ------------------------------------------------------------------------------------------------ #
# Positively selected genes: Unique to Marine OR Terrestrial snakes
# PAML -> Only genes where no signal of selection in background branches after dropping foreground
# HyPhy -> Only 'selection associated with trait' entries (FG/BG dist. can be the same)
# PSGs MUST be predicted by both tools

# Marine (Hydrophis) # 1,402
psg.marine.hyphy.paml <- bustedph$`test results corrected` |>
  left_join(paml) |>
  filter(
    str_detect(result, pattern = 'Selection associated with trait'),
    signal == 'PS_fg'
  ) |>
  pull(file)

write_lines(
  x = psg.marine.hyphy.paml,
  file = here(outdir,'PSGs-marine.txt')
)

# Terrestrial # 484
psg.terrestrial.hyphy.paml <- bustedph.terrestrial$`test results corrected` |>
  left_join(paml) |>
  filter(
    str_detect(result, pattern = 'Selection associated with trait'),
    signal == 'PS_bg'
  ) |>
  pull(file)

write_lines(
  x = psg.terrestrial.hyphy.paml,
  file = here(outdir, 'PSGs-terrestrial.txt')
)

# Sanity check: No Marine genes should be in Terrestrial genes
table(psg.marine.hyphy.paml %in% psg.terrestrial.hyphy.paml)

# ------------------------------------------------------------------------------------------------ #
# Positively selected genes: Signal in Marine AND Terrestrial
# HyPhy -> Selection acting on FG and BG branches (Dist. can be significantly different or the same)
# PAML -> Reported as PS in both BG and FG after performing dropout analysis
# PSGs MUST be predicted by both tools

# PSGs shared by Marine and Terrestrial snakes # 532
psg.shared.hyphy.paml <- bustedph$`test results corrected`|>
  filter(str_detect(result, 'Selection acting on branches with phenotype')) |>
  select(file) |>
  left_join(bustedph.terrestrial$`test results corrected`) |>
  filter(str_detect(result, 'Selection acting on branches with phenotype')) |>
  select(file) |>
  left_join(paml) |>
  filter(signal == 'PS_fg_bg') |>
  pull(file)

write_lines(
  x = psg.shared.hyphy.paml,
  file = here(outdir, 'PSGs-shared.txt')
)

# Sanity check: No shared genes should be in Marine/Terrestrial unique PSGs
table(c(psg.marine.hyphy.paml, psg.terrestrial.hyphy.paml) %in% psg.shared.hyphy.paml)

# ------------------------------------------------------------------------------------------------ #
# Insignificant genes: Genes not under selection in either Marine OR Terrestrial OR Marine & Terrestrial
# Thes are genes that are not identified as being under positive selection in Marine, Terrestrial
# or shared conditions.

# All PSGs (unique/shared)
all.psg <- c(psg.marine.hyphy.paml, psg.terrestrial.hyphy.paml, psg.shared.hyphy.paml)

# Neutral/non-PSG genes in dataset # 6,236
paml$file[! paml$file %in% all.psg] |>
  write_lines(
    file = here(outdir, 'neutral-genes.txt')
  )

# ------------------------------------------------------------------------------------------------ #
# Relaxation/Intensification
# Write RELAX results to file after classifying if:
#   - The orthogroups reach significance or not in the Marine clade
#   - Whether there is a signal of intensification/relaxation of selection
annotations <- read_csv(
  here('orthologs','ortholog-annotation','results','ortholog-annotation','orthologs.csv'),
  col_names = TRUE,
  col_types = cols()
) |>
  select(orthogroup, symbol)

relax$`test results corrected` |>
  rename(k = `relaxation or intensification parameter`) |>
  mutate(
    signif = ifelse(adj_pval <= 0.01, 'Significant', 'Insignificant'),
    grouping = case_when(
      k > 1 ~ 'Intensification',
      k < 1 ~ 'Relaxation',
      k == 1 ~ 'Neutral'
    )
  ) |>
  left_join(annotations, by = join_by(file == orthogroup)) |>
  select(orthogroup = file, symbol, lrt, pval, adj_pval, k, signif, grouping) |>
  arrange(adj_pval) |>
  write_csv(
    file = here(outdir,'relax-corrected.csv'),
    col_names = TRUE,
    na = ''
  )
