# ------------------------------------------------------------------------------------------------ #
# Table: EDTA summary table
#
# Script parses results from the EDTA summary file and generates a single table of multiple
# species. The output from this script is a single, long-format table that needs to be edited
# manually to form the final table (but could leave long-format if you'd like).

# ------------------------------------------------------------------------------------------------ #
# Libraries
library(tidyverse)
library(here)

# ------------------------------------------------------------------------------------------------ #
# Functions
#
# parseSum: parses the summary file generated by EDTA and generates a simple table from it.
parseSum <- function(path) {
  # File name
  fn <- sub('\\..*', '', basename(path))

  sum.str <- read_lines(path)


  # Get index of final line of interest
  idx.start <- grep('^Class', sum.str)
  idx.end <- grep('^Total\\s+', sum.str)[3]

  # Subset vector
  sum.str <- sum.str[idx.start:idx.end]

  # Column names
  cnames <- unlist(str_split(sum.str[1], pattern = '\\s+'))

  # Conver rest of data to a table
  tmp <- str_split(sum.str[3:length(sum.str)], pattern = '\\s+')
  tmp <- map(tmp, \(x) { z <- x[x != '']; z <- z[length(z) == 4]})
  tmp <- list_flatten(tmp)[lengths(list_flatten(tmp)) != 0]
  tib <- as_tibble(
    x = reduce(.x = tmp, .f = rbind),
    .name_repair = 'unique'
  )
  colnames(tib) <- cnames

  # Clean table
  tib |>
    mutate(
      across(
        2:4,
        ~ sub('--', '', .x)
      ),
      `%masked` = sub('\\%', '', `%masked`),
      across(2:4, as.numeric),
      sample = fn
    ) |>
    select(sample, everything())
}

# ------------------------------------------------------------------------------------------------ #
# Import summary tables
sum.files <- fs::dir_ls(
  path = here('assembly'),
  glob = '*.sum',
  recurse = TRUE
)

sum.df <- map(sum.files, parseSum) |>
  list_rbind() |>
  filter(sample != 'aipysurus_laevis') |>
  mutate(
    sample = case_when(
      sample == 'hydmaj-p_ctg-v1' ~ 'Hydrophis major',
      sample == 'hydrophis_curtus-garvin' ~ 'Hydrophis curtus (AG)',
      sample == 'hydrophis_elegans' ~ 'Hydrophis elegans',
      sample == 'hydrophis_ornatus-garvin' ~ 'Hydrophis ornatus'
    )
  )

# ------------------------------------------------------------------------------------------------ #
# Write summary info to CSV in long format. REQUIRES EDITING POST EXPORT!
sum.df |>
  write_csv(
    file = here('figures', 'supplementary', 'table-x-repeats-summary.csv'),
    col_names = TRUE
  )
