# ------------------------------------------------------------------------------------------------ #
# RepeatMasker summary tables
#
# This code summarises the summary tables generated by RepeatMaskers 'buildSummary.pl' script.
# The output is a table with counts, lengths and percentages for each of the annotated repeats.
# This script parses the table from the output file and formats it into a TSV. Further, I take
# the top 5 repeats (by %) within each broader class and present them, while clumping the remaining
# repeats into 'other' (usuall a few percent at most). I also calculate the total repeats per Class.

# ------------------------------------------------------------------------------------------------ #
# Libraries
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
})

# ------------------------------------------------------------------------------------------------ #
# Parsing function
parseSummary <- function(path) {
  fn <- sub('\\..*', '', basename(path))

  lines <- read_lines(path)
  cnames <- unlist(str_split(lines[5], '\\s+'))
  classes <- list()

  # Lines as list split on white space
  lines <- str_split(lines[7:grep('total interspersed', lines)], '\\s+')
  lines <- imap(lines, \(x, i) {
    if(x[1] != '') {
      if(x[1] == 'DIRS') {
        classes[i] <<- 'DIRS_toplevel'
        x[1] <- 'DIRS_toplevel'
      } else {
        classes[i]  <<- x[1]
      }
    }
    z <- x[x != ''];
    z <- z[length(z) == 4]
  })

  # Classes tibble
  classes <- tibble(
    Class = unlist(classes),
    Class2 = unlist(classes)
  )

  # List to tibble
  tib <- as_tibble(
    x = reduce(.x = lines, .f = rbind),
    .name_repair = 'unique'
  )
  colnames(tib) <- cnames

  # Clean table
  df <- tib |>
    mutate(
      across(
        2:4,
        ~ sub('--', '', .x)
      ),
      `%masked` = sub('\\%', '', `%masked`),
      across(2:4, as.numeric),
      sample = fn
    ) |>
    full_join(classes) |>
    fill(Class2, .direction = 'down') |>
    rename(`Sub-class` = Class, Class = Class2) |>
    select(sample, Class, `Sub-class`, everything()) |>
    mutate(
      Class = str_replace(Class, 'DIRS_toplevel', 'DIRS'),
      `Sub-class` = str_replace(`Sub-class`, 'DIRS_toplevel', 'DIRS'),
      Class = factor(Class, levels = unique(Class)),
    ) |>
    group_by(Class) |>
    arrange(Class, -`%masked`, -bpMasked)

  # Bit of formatting
  df |>
    (\(x) split(x, x$Class))() |>
    imap(\(x, y) {
      # Remove NA rows (unless Class == Sub-class)
      df <- x |>
        filter(!if_all(c('Count', 'bpMasked', '%masked'), \(i) is.na(i)))

      # Total count/length of repeats for class
      df.total <- df |>
        group_by(sample, Class) |>
        summarise(
          `Sub-class` = 'Total',
          Count = sum(Count),
          bpMasked = sum(bpMasked),
          `%masked` = sum(`%masked`)
        )

      if(nrow(df) > 5) {
        # Top 5 most abundant
        n5 <- df |> slice(1:5) |>
          ungroup()

        # Collapse the rest of the repeats and aggregate counts
        other <- df |>
          slice(6:nrow(df)) |>
          group_by(sample, Class) |>
          summarise(
            `Sub-class` = 'Other',
            Count = sum(Count),
            bpMasked = sum(bpMasked),
            `%masked` = sum(`%masked`)
          )

        # Bind together
        df <- bind_rows(n5, other)
      }

      df <- df.total |>
        bind_rows(df)

      if(nrow(df) == 2) {
        return(df |> slice(1))
      }

      return(df)
    }) |>
  list_rbind() #|>
  # mutate(
  #   Class = as.character(Class),
  #   Class = ifelse(Class != `Sub-class`, NA_character_, Class),
  #   `Sub-class` = ifelse(is.na(Class), `Sub-class`, NA_character_)
  # )
}

# ------------------------------------------------------------------------------------------------ #
# Write repeat tables to file
fs::dir_ls(
  path = 'assembly',
  glob = '*.fa.summary',
  recurse = TRUE
) |>
  as.character() |>
  (\(x) set_names(x, sub('\\..*|-garvin.*', '', basename(x))))() |>
  map(parseSummary) |>
  imap(\(x, id) {
    write_csv(
      x,
      file = here('tables',glue::glue('repeats-rm-{id}.csv')),
      col_names = TRUE
    )
  })
